// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FiltertestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filtertest() {
    driver.get("https://www.thegioididong.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.id("skw")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(6) i > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("skw")).sendKeys("samsung");
    driver.findElement(By.id("skw")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,1700)");
    driver.findElement(By.cssSelector("#dtdd .boxNew__item:nth-child(5) .lazyloaded")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".main-menu > .active")).click();
    driver.findElement(By.cssSelector(".active > a > span")).click();
    driver.findElement(By.cssSelector(".block-manu span")).click();
    driver.findElement(By.cssSelector(".filter-list--hang:nth-child(1) > .c-btnbox:nth-child(2) > img")).click();
    driver.findElement(By.linkText("Xem 22 kết quả")).click();
    driver.findElement(By.cssSelector(".warpper-price-outside > .filter-item__title")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".noUi-active"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".noUi-active"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".noUi-active"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#slider-range .noUi-connect > .noUi-handle")).click();
    driver.findElement(By.cssSelector(".filter-button:nth-child(3) .total-reloading")).click();
    driver.close();
  }
}
